project_name: reservation-salles

builds:
  - id: cli
    main: ./cmd/cli
    binary: cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: server
    main: ./cmd/server
    binary: server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

release:
  disable: true
